dist: xenial
branches:
  only:
  - master
  - develop
language: node_js
node_js: '10'
cache:
  directories:
  - node_modules
jobs:
  include:
  - script:
    - npm install && npm run lint && npm run build && npm run test
    name: Build Outreach-Interviews
stages:
- test
notifications:
  slack:
    secure: xhuIPz8DpmBhgivWajgpB0crqv67ltbihIaFuW0lPOVHp5L7kmd/pwE1yS4ncR7dNrh622yaxEKuLsGL4zX2Va1JbcifDy9VxRajErVmZiGUEedblddSZACE7DdVAk0xmvNQxdmPeCKggx0MeErvSOeW9GzqmLAWPXHn9Fo1j4VZ8+xXVlQnNcMvVzARtKB5ndwsJOKH/MGM71MD6ZpfaV2lrVISMuJyKAl6btWdwuGS6WhjwK5b4vv7FGHw19lRJwQiJQcOiEnIlnjKU4Alg1x+j7aOk66vBwO2DBc/+fs2fAFr1fD1Huie/3poXiHELJRf3P5vMAeYzoWJ0bVDOvJMduGQeQBTarJYvN647O4lOz/q0Ehe7hxcKAuPrYSeIOjt7ejTX+Mcx2B6dEqZMDX530l14LBlakNlJ64os+Df8YmD5T3Ea2OkueUuoX/xq9fZK+KyxIN1G34I8RHw3bf5npomS6xyyzY8lOpgWgm//zr3Geu79RUZAVWL6luV8uPJvlj5qiyZz+GUggXzclxpSVbzhfDw9bvZl07kztpDRb3UDtX3HgIiU6dIZ6WjNUrqMfovVADO+3tk/2cMwS8oL5yiu7U409oKM/C15P2HckVbUSiDzxjt6N/CG6a/pcthwDX+N7lK8T7GFBmhmkQwEm5AkCJD/LmSqtOiG5Y=
  email:
    recipients:
    - patrique.legault@uottawa.ca
env:
  global:
    secure: nXQ8KYec9k0qQYp7Jj4FUqvsb/g9cCigVybmPM5cIQaEXN076P9a5gP5AOS5iAsxPm4vewUf6mCV9BfAKEfmyPel2IPRAAep+TPw3DuEyXYoPhQUS1oBdbjFgFLwhj8og/YUg4DgCR90wJ9Yrn4YyVDLFVW1St7tFQEvIikJ+19hGYv5LjzBvo9gYpshZ6lrOVGYfkB+VJr9Cmc92njIraoqgaCWQhZuaOcr3yN2ux2lUjO0kJ8X80w4nKdMo4a+cRwPhG92wOcRWdbUZYqPQKu5VjIIbbpf5BYTphEf9wGHG6n8US4eNFWUy+VobEYesmHO3YZRGXne49xkoJQ/GuIDA9NFwTCCqsPzD4YyzeXmjtQ+BXb1BjdIm8k2TmIrguAM9BfxJ8okLVmW5zNMk5Dg+DETWhqCOnR43EX7u8DoJQP99STvRSLWeVyiJVvDzyKovctFhIojmM7Twpqp96UX9tiM7Je5J27uoVj3I5bgaQNMhyRccpP9edA20n0DFzF/BdyGJVUo/FOujcIP1u4o+tU781fA9o0fSX9wYQoiNd6nBHg2oRCtWmv7V2WgsxIiEiY7UzlnecxfJT1avuoJLnjFX25iih/uv3YpV4EDrojq0BDu39rCzosf+k3U4yEA98oFwNsBMe4GLKA+IWLrLtF/sggIvoO4XPs72qw=
